POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "harsh","password":"Pass123"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "harshkulkarni","password":"Password123", "email": "harshkulkarni@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token <token_key>

{}
